# Generated by Django 5.2.1 on 2025-06-09 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name_plural': 'customer'},
        ),
        migrations.AlterModelOptions(
            name='items',
            options={'verbose_name_plural': 'products '},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name_plural': 'Orders '},
        ),
    ]
