# Generated by Django 5.2.1 on 2025-08-07 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_profile_old_cart'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='adress2',
            new_name='address2',
        ),
        migrations.AlterField(
            model_name='profile',
            name='data_modified',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
